# Generated by Django 4.2.5 on 2024-08-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='udept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='urole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='usex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='ustat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lims.status'),
        ),
    ]
